### ISSUE TITLE
When you prompt open it is taking password , it is running only one command ?

### ISSUE THREAD

**Issue by himanshuoodles** [jorangreef/sudo-prompt#24]
i want to run like this.
but only first command is running and other have error
```
var sudoP = require('sudo-prompt');
var options = {
name: 'Productivity app',
icns: '/path/to/icns/file', // (optional)
};
sudoP.exec('apt-get install -y xdotool', options, function(error, stdout, stderr) {
console.log("stdout",stdout,"stderror",stderr);

});

sudoP.exec('xdotool', options, function(error, stdout, stderr) {
console.log("stdout",stdout,"stderror",stderr,"error",error);



});

sudoP.exec('apt-get install -y gawk', options, function(error, stdout, stderr) {
console.log("stdout",stdout,"stderror",stderr,"error",error);



});
```
![screenshot from 2016-06-01 11 33 26](https://cloud.githubusercontent.com/assets/15084072/15699746/01820502-27ed-11e6-828d-a96d418ed95e.png)

**Comment by jorangreef** [comment]
Fixed by https://github.com/jorangreef/sudo-prompt/commit/1e11485bf4686e9cf12b82541aec9761d573f1ed

This was a bug in `gksudo`, which cannot be used to run multiple commands concurrently. It uses a lock file and exits if the lock file exists. I am not sure if there is a flag to disable this behavior in `gksudo` so I have removed support for `gksudo`.

Also, just on the side, I noticed that your test program runs `apt-get install -y xdotool` and then immediately runs `xdotool`. You should rather wait for the callback from the installation of `xdotool` to return before you assume that `xdotool` is installed. Otherwise, your program may try to run `xdotool` before the installation has finished.
