### ISSUE TITLE
Is it possible to pass in parameters when running a batch file?

### ISSUE THREAD

**Issue by junjunruan** [jorangreef/sudo-prompt#30]
Hi,
I am working on Windows, my batch file has some if-else statement for different commands, for example,
```
IF condition1 (c:\Windows\System32\schtasks.exe /Create ...)
Else (c:\Windows\System32\schtasks.exe /delete ...)
```
I hope with sudo-prompt, we can pass parameters like the following syntax, so that I can verify the if condition above by comparing with the passed parameter value.
```
var sudo = require('sudo-prompt');
var options = {
  name: 'Electron',
  icns: '/Applications/Electron.app/Contents/Resources/Electron.icns', // (optional)
};
sudo.exec('echo hello', [args] ,options, function(error, stdout, stderr) {});
```
If with current package, there is other ways to achieve my goal, please let me know.

Thanks,

**Comment by jorangreef** [comment]
Hi @junjunruan, `sudo.exec()` is similar to `child_process.exec()` in that you simply pass the arguments as part of the command string (see the [Node.js docs](https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback)). There is therefore no `[args]` argument when calling `sudo.exec()`.

If you need to pass parameters to your batch file, just pass "test.bat arg1 arg2 ..." as your command string. You then need to know how to access arguments from within a Windows batch file (see [StackOverflow](http://stackoverflow.com/questions/26551/how-to-pass-command-line-parameters-to-a-batch-file)).

**Comment by junjunruan** [comment]
Thanks @jorangreef. It works.

I have a few questions. Is it the right place to ask questions or is there other ways to contact you?
My questions are:

1. From your documentation, I see this message: Passing options.name or options.icns is currently not supported by sudo-prompt on Windows. Then what the syntax should be for windows?
I tried delete options json, and remove "options" from sudo.exec(), it doesn't work.
The only way it works for me now is leave options json and parameter there.

2. I have several commands in my .cmd batch file need admin right, is there any ways to remember user's choice ("Yes") in the first time so that the dialog doesn't need to prompt every time?
(maybe save the windows username and password when the first time a user clicks yes?)

3. What if the user click "NO" when the dialog popup (user did not grant permission), is there any ways to keep popup the dialog until user choose YES?

**Comment by jorangreef** [comment]
Sure, you're welcome to ask here and it might be helpful to others. Regarding your questions:

1. Just pass `{}` as options on Windows.

2. No, we delegate the privilege elevation to Windows itself. Windows shows the dialog prompt and we never receive the username and password (this would also not be safe). The best thing is to create a batch script which does everything that requires admin rights, and then execute this batch script using sudo-prompt's `exec()`. That way the user will only receive a single password prompt each time you run the batch script.

3. Sure, you could just call `exec()` again but this would be annoying to the user. Perhaps you could explain to the user in advance why you need admin privileges, so that they are more likely to accept?

**Comment by junjunruan** [comment]
Thanks for your quick response @jorangreef.

Here is what I tried based on your suggestion:
1.  I got an error: "process.title cannot be used as a valid name" after I changed to the following code:
```
process.title = "electron";
 sudo.exec('echo hello', {}, function(error, stdout, stderr) {});
```
I checked the default value of process.title, the result is some Unrecognizable code.

2. I think what you mean if put all the commands need admin right in a batch file, then have one sudo.exec() to run at once. 
But in my case, I have several sudo.exec() in my code by passing different parameters to run the batch file.
```
sudo.exec('test.cmd param1', options, function(error, stdout, stderr) {});
sudo.exec('test.cmd param2', options, function(error, stdout, stderr) {});
```
My batch file is similar to:

```
    if(param1) run command1
    if(param2) run command2
```

**Comment by jorangreef** [comment]
Sure,

1. It may be that your process title was not in English? `sudo-prompt` requires `options.name` to be alphanumeric, and uses the process title if `options.name` is not provided. To solve this, just try  using`{ name: 'Test' }` as your `options` object instead of `{}`.

2. Then you would need two prompts, unless you can restructure things.

**Comment by junjunruan** [comment]
Thanks @jorangreef:
Yes, the process title is some weird characters that I didn't recognize. But with `{ name: 'Test' }`, it works.
