### ISSUE TITLE
How to detect if command run terminates

### ISSUE THREAD

**Issue by BrainyBrian** [jorangreef/sudo-prompt#37]
Hi!
Just curious as to how I would detect if the command terminates. I tried setting the exec to a variable and doing variable.on(....) as I would to a normal async child process.

Is there any way I can do that?

Does this run the command asynchronously?

**Comment by jorangreef** [comment]
Thanks @BrainyBrian 

To confirm, your command will be run asynchronously in another process.

Your callback will be called as soon as your command terminates:

```javascript
sudo.exec('echo hello', options,
  function(error, stdout, stderr) {
    console.log('command terminated');
  }
);
```

`sudo-prompt` exec() is different to that of `child-process` since it needs to deal with permissions issues on different platforms. It does not return a child process instance.
