### ISSUE TITLE
Permission error copying files

### ISSUE THREAD

**Issue by debelop13** [jorangreef/sudo-prompt#38]
Hello,

I had permission errors like this "Uncaught Error: EACCES: permission denied, open" or like this "Uncaught Error: EACCES: permission denied, mkdir".

And for this reason, I use this npm module (sudo-prompt)

My code is ..

var toExec = "chown -R $(whoami) "+ pathToCopy;
sudo.exec(toExec, options, function (error, stdout, stderr) {
    startCopying();
});

But I receive "command failed"  

What am I doing badly?

Thanks

**Comment by jorangreef** [comment]
I tried the following on macOS 10.12.2 and it worked fine:

```
var sudo = require('sudo-prompt');
var command = "chown -R $(whoami) testdirectory";
sudo.exec(command, {}, console.log);
```

What does `which whoami` return?

Are you sure that `pathToCopy` exists?

What platform are you on?

Do you know that `whoami` when run under sudo will probably return `root`? You may want to get the user name outside of the sudo session first.

**Comment by debelop13** [comment]
Yes path exists, I am in darwin and win32, crossplatform app.

Maybe I should reformulate the question: 

I am doing an installer and I want to give permissions to user to make various directories and copy files.
Do you know how I can execute a javascript function with privileges?

Thanks!

**Comment by jorangreef** [comment]
> Yes path exists, I am in darwin and win32, crossplatform app.

Your command as you gave it above will most likely not work on win32, since win32 does not have chown

You can use `sudo-prompt` to execute any shell command within a sudo session. For instance, if you need to execute a javascript function with privileges as you say then you could use `sudo-prompt` to launch `node script.js`. But from there, the rest is up to you.

Some suggestions:

1. Do the simplest thing possible first, then build from there.
2. Test your command in the terminal first on all platforms to make sure it works. If it does not work in the terminal then it will not work in `sudo-prompt`.
3. Make sure you do not rely on any environment variables or current working directory when executing your command. Use absolute paths.

**Comment by debelop13** [comment]
Hi,

I'm sorry but I'm little lost:

Now, I have node script (js) that copy all files.
This script is called by sudo-prompt like this:

        var command = 'node ' + path.resolve(__dirname, '../vendor/installer/installationsudo.js') + ' "' + parameter + '"';

        sudo.exec(command, options, function (error, stdout, stderr) {
            if (error) {
                console.log(error)
                self.set('installationResults', error);
                self.set('installationFinished', true);
            } else {
                console.log(stdout)
                console.log(stderr)
                self.set('installationResults', "Installation done.");
                self.set('installationFinished', true);
            }
        });

This code works in debug mode, but not compiled with electron.

I am using electron v1.5.0 (with node v7.4.0), I thought that was for something wrong in my script, but if I execute this, also fails:

 var command = 'node -v'';
        sudo.exec(command, options, function (error, stdout, stderr) {
            if (error) {
                console.log(error)
            } else {
                console.log(stdout)
                console.log(stderr)
            }
        });

And I have same problem, in debug mode all is ok but once compiled no works.

I know that is not a problem with sudo-prompt, but I hope that you can help me, thanks!

**Comment by jorangreef** [comment]
Your second example `var command = 'node -v'';` has an extra single quote at the end of the line which would not compile.

It may also be that when Electron runs, it runs using a different environment, so you need to reference the node binary using an absolute path. Probably `/usr/local/bin/node` instead of just `node`.
