### ISSUE TITLE
Add support for running command in a sudo shell on Linux (as already on Windows and macOS)

### ISSUE THREAD

**Issue by LouWii** [jorangreef/sudo-prompt#39]
Hi there,

Thanks for creating that package, it's really handy.

However, I have a small issue with it.
I need to run 2 commands with root rights.

If I do
```
    sudo.exec('command1', options, function(error, stdout, stderr) {
      if (!error){
        sudo.exec('command 2', options, function(error, stdout, stderr) {
          if (!error){

          } else {
            console.error(error);
            console.log(stderr);
          }
        });
      } else {
        console.error(error);
        console.log(stderr);
      }
    });
```
It works, but the app will ask twice for the root password, which is annoying for the users.

I tried doing
```
    sudo.exec('command1; command2', options, function(error, stdout, stderr) {
      if (!error){
        
      } else {
        console.error(error);
        console.log(stderr);
      }
    });
```
So they run at the same time, but that fails. The command2 fails because it doesn't have root rights.

Happening on Ubuntu 16.04

Am I missing something ?

**Comment by jorangreef** [comment]
Thanks @LouWii , you are welcome.

The reason for the multiple password prompts is because Ubuntu uses TTY tickets, so each separate shell session requires sudo.

`sudo-prompt` uses a privileged shell session on Windows and Mac, so your command should work fine there as is. On Linux, however, we are currently running the command directly using kdesudo or pkexec, so your second command would fail since it would be outside of the sudo session. I think this would be good to fix.

In the meantime, could you try: `bash -c "command1; command2"` as your command argument?

**Comment by LouWii** [comment]
`bash -c "command1; command2"` does work. Thanks !

What would you recommend as a long-term fix for Linux ? Use something different than `kdesudo` or `pkexec` ? I know Linux a bit but this goes beyond my knowledge.

**Comment by jorangreef** [comment]
Great! I would like to update the Linux component of `sudo-prompt` to do something similar by default.

**Comment by franciscop** [comment]
What about something like this?

```js
const sep = '~SEPARATOR~';

const cmd = (...commands) => {
  const separated = commands.join(` ; echo "${sep}"; `);
  return (await exec(`bash -c '${separated}'`)).split(sep);
};
```

Then to use it you can do:

```js
const [root, echo, home] = await cmd('ls /', 'echo "Hello world"', 'ls ~/');
```
