### ISSUE TITLE
Add long-running proxy

### ISSUE THREAD

**Issue by igor-lemon** [jorangreef/sudo-prompt#43]
Hi Joran. I have a small issue. You wrote in documentation that if tty_tickets is disabled than we'll ask password only once but also with disabled tty_tickets promt shows for each exec call but if I input some command in terminal after that I can use exec command much times without password promt.
Also maybe do you have some ideas how to resolve troubles with enabled tty_tickets? Because I want to ask root permissions only once and after use needed commands also after close/restart app (sudo-prompt + electron).

**Comment by jorangreef** [comment]
Thanks Igor. Would you please provide a small test case to reproduce with tty_tickets disabled? What platform is that on?

I have been thinking about how to work with enabled tty_tickets. It may be worthwhile for sudo-prompt to have a persistent privileged child process (launched the first time sudo.exec() is called) which can be used for subsequent calls. This would work as long as the process remains live.

For permission that would last across reboots, that's dangerous from a vulnerability point of view. It can be done with a setuid binary but then the app would need a way to authenticate with the binary so that the binary can't be exploited by other processes. This kind of authentication would be easy if the app has an in-memory token, but I don't know how to persist that across reboots. Perhaps there may be another way for the setuid binary to authenticate that it really is the app that's calling, but even then, one would need to lock the app down and make it read only (otherwise a hostile process could overwrite some of the source of the app).

**Comment by igor-lemon** [comment]
Yep, I reproduced. I'm using macOS Sierra. With disabled tty_tickets ask password per each request too but if I input some sudo command in terminal I can exec any command without password promt.

What do you think about up a small sudo sh/bash process and after exec all sudo commands through that process (Linux + macOS)? As example I found I a forked electron-sudo rep and found that we can do that I wrote above.
https://github.com/ppoffice/electron-sudo
And after make something like that
`
let options = {name: 'Application'},
     sudoer = new Sudoer(options);
...
function sudoTest(command) {
if (!this.cp || this.cp.exitCode !== null) {
    sudoer.spawn('/bin/sh', []).then(cp => {
       this.cp = cp;
       this.cp.stdin.write(`${command} \n`);
    });
} else { 
  this.cp.stdin.write(`${command} \n`);
}
}
`
That solution is works on Linux and macOS but has troubles on macOS Sierra :(

**Comment by jorangreef** [comment]
> What do you think about up a small sudo sh/bash process and after exec all sudo commands through that process (Linux + macOS)

Yes, this was what I would like to do.

**Comment by treyreynolds** [comment]
You are able to disable tty_tickets on your own machine if that helps with your use case. My application is only loaded onto custom machines so I am able to edit /etc/sudoers as mentioned in this article:
[TTY Tickets Option Now on by Default for MacOS Sierra](https://derflounder.wordpress.com/2016/09/21/tty_tickets-option-now-on-by-default-for-macos-sierras-sudo-tool/)

> If you want sudo to return to using the pre-Sierra behavior on macOS Sierra, edit /etc/sudoers to add the following option:
`Defaults  !tty_tickets`
