### ISSUE TITLE
Sudo permissions to run a node.js code block

### ISSUE THREAD

**Issue by carloscuba** [jorangreef/sudo-prompt#47]
Hello there,

Thanks for your great work on the sudo-prompt module!

I’m building an Electron App that needs to send UDP packages and I’m using a module called [Cap](https://github.com/mscdex/cap) to access an interface, open it and send the package through it. Locally, it runs without any problems, but when running the App on other Macs (I sent the App.app to a couple of fellows to help me with the testing) an error message appears **Uncaught Error: (cannot open BPF device) /dev/bpf0: Permission denied**.

If they start the App via the Terminal running `sudo Electron-app.app/Contents/MacOS/Electron-app` no error is thrown, so definitely it’s an issue related to User Permissions and that is why I searched for available sudo modules for Electron. 

I don’t need to run a specific command as root, but I do need to grant the App with sudo privileges on this specific section (specifically on the `c.open()` line -which is throwing the error-):

```
var Cap = require(‘cap’).Cap,
        c = new Cap(),
        device = Cap.findDevice(‘192.168.0.20’),
        filter = ‘arp’,
        bufSize = 10  1024  1024,
        buffer = new Buffer(65535);

var linkType = c.open(device, filter, bufSize, buffer);
```

I’m trying to use your package this way:  
```
sudo.exec(‘su’, options, function(error, stdout, stderr) {
  linkType = c.open(device, filter, bufSize, buffer);
})
``` 

in order to get the required privileges but it seems not to be working (or I’m using it wrong). Have you seen or know a way to start the complete Electron App with sudo privileges (asking for the root password on the startup) or is there something I’m missing?

Thank you very much in advanced!
I’ll be waiting for your response.

**Comment by jorangreef** [comment]
Thanks @carloscuba 

`sudo.exec(‘su’...` switches to the root user, but only within the context of the shell from which it is called (the child process launched by `sudo-prompt` to run your command). That is why your Electron App does not automatically receive any sudo privileges - it is outside of the shell launched by `sudo-prompt`.

> Have you seen or know a way to start the complete Electron App with sudo privileges
I would not recommend launching your complete GUI app with sudo privileges, see: https://github.com/jorangreef/sudo-prompt#non-graphical-terminal-commands-only

You could use `sudo-prompt` to launch a non-GUI Node script with sudo privileges, which will then open the device using cap and release its sudo permissions once the device is open. `sudo-prompt` does not provide a way to do IPC between processes, since it's difficult to emulate Node's child-process module exactly (we do several things under the hood to make the permissions prompt work), so you will need to use files or a unix socket to communicate. Make sure to downgrade your privileged script as soon as possible so it can't be exploited by other programs.

**Comment by pabloneill** [comment]
Hey,

Thanks for your work on this . I'm  trying to use this sudo-promt to start a child process on a raspberry PI, tha needs sudo to execute. 

I am trying this : 

```
var sudo = require('sudo-prompt');
const execFile = require('child_process').execFile:
const child = sudo.execFile('/home/pi/Desktop/fm_transmitter/bin/Release/fm_transmitter' , ['high_dash.wav', '103.40'], (error,stdout, stderr) => {
  if (error) {
    throw error;
  }
  console.log(stdout);
});
}
```

But is returning TypeError: sudo.execFile is not a function

I'm also trying:

```
var sudo = require('sudo-prompt');
const child = sudo.exec('/home/pi/Desktop/fm_transmitter/bin/Release/fm_transmitter', ['high_dash.wav', '103.40'], (error,stdout, stderr) => {
  if (error) {
    throw error;
  }
  console.log(stdout);
});
}
```
But that is returning: 

Usage: /home/pi/Desktop/fm_transmitter/bin/Release/fm_transmitter [FILE] [Frequency]  which are the two arguments required. I'm trying to figure out where I should place these?

As you've probably noticed, I'm technically out of my debt here but any insights would be greatly appreciated!

**Comment by karthik93advaitha** [comment]
@jorangreef : Thank you for the tip on sudo. Im trying to change the user from A  to B to execute commands on remote host from my node application. I'm not able to get any response for executing 'su' using child_process module. any other module you would recommend for me to try?

**Comment by jafri** [comment]
@jorangreef how would you use sudo-prompt to launch a non-GUI Node script with sudo privileges in electron?
