### ISSUE TITLE
Sudo App does not exit on Mac where direct child process already exits.

### ISSUE THREAD

**Issue by imdreamrunner** [jorangreef/sudo-prompt#57]
Dear author and other developers,

I find `sudo-prompt` a very useful and handy tool. Recently I encounter an issue while using it:

I have an node application that will launch a process A, and process A will fork a new process B. And then process A will terminates. (Process B is not sub-process of process A)

If I run process A in Terminal directly, I can see it quit normally as well. However when I use sudo-prompt on Mac, the Sudo App does not exit, and the node callback is not called unless I kill process B.

May I know how should I get Sudo App quit and node callback called while keep a separate process B running?

**Comment by jorangreef** [comment]
Thanks @imdreamrunner 

Process A will not terminate naturally until the outstanding callback returns, which happens only when process B terminates.

Since process B will not terminate, process A will not terminate.

What you could do for now is to write a plain file to send a message from process B to process A, as soon as process B is running, and then manually call `process.exit()` in process A to terminate process A when process A sees the file.

I am thinking through how to add support for `spawn` to sudo-prompt and will bear your use-case in mind.

**Comment by imdreamrunner** [comment]
Dear @jorangreef 

Thank you very much for your informative reply.

The interesting thing is I use double-fork to create process B and process A has actually already terminated. (Maybe I should create a runnable example to show the case. Let me do more research first.)

May I know if the MacOS application is opened source? Maybe I can take a look for adding support spawn.

Again many thanks for your reply!

**Comment by jorangreef** [comment]
Closing for now, please let me know if I can help further with this.
