### ISSUE TITLE
Elevation prompt not shown and "User did not grant permission" on macOS 10.12.6

### ISSUE THREAD

**Issue by jviotti** [jorangreef/sudo-prompt#64]
See https://github.com/resin-io/etcher/issues/1860.

@craig-mulligan tried running the usage example:

```js
sudo.exec('echo hello', {},
  function(error, stdout, stderr) {
    if (error) throw error;
    console.log('stdout: ' + stdout);
  }
);
```

But all he gets is:

```js
/Users/gaudi/work/sudo-test/index.js:8
    if (error) throw error;
               ^

Error: User did not grant permission.
    at ReadFileContext.callback (/Users/gaudi/work/sudo-test/node_modules/sudo-prompt/index.js:316:49)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
```

without any prompt at all.

I unzipped the applet to see if I could debug things myself, but got stuck a bit. The AppleScript file calls `sudo-prompt-script`, which then calls `/bin/bash sudo-prompt-command 1>stdout 2>stderr`, but I can't see the source of `sudo-prompt-command` anywhere.

Maybe you have some suggestions to debug this further?

**Comment by jorangreef** [comment]
Thanks @jviotti,

The source of the `sudo-prompt-command` script is written out dynamically during `exec()` here: https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L244

If the `code` file is not found (`ENOENT`) we assume that a privilege error occurred. But if the elevation prompt is not shown it's possible that something else went wrong in between `MacOpen()` and `MacResult()`.

@craig-mulligan, would you please try the following and let me know what you get for each?

```
which mkdir touch bash echo chown
```

```
osascript -e 'do shell script "echo foo" with administrator privileges'
```

```
sudo -k
sudo echo bar
```

**Comment by craig-mulligan** [comment]
Hey @jorangreef 👋 
Sure, here's the output for each:
```
➜  sudo-test which mkdir touch bash echo chown
/bin/mkdir
/usr/bin/touch
/bin/bash
echo: shell built-in command
/usr/sbin/chown

➜  sudo-test osascript -e 'do shell script "echo foo" with administrator privileges'

osascript: can't open default scripting component.
➜  sudo-test sudo -k
sudo echo bar
Password:
bar
```

**Comment by jviotti** [comment]
Looks like a problem with the AppleScript interpreter. According to https://discussions.agilebits.com/discussion/64048/the-operation-couldnt-be-completed-osascript-cannot-open-default-scripting-component, this can happen due to a broken macOS installation. @craig-mulligan could it be that installing bootcamp messed up your system?

One of the guy says:

> You may wish to try repairing your disk with Disk Utility (in /Applications/Utilities) first and see if that helps.

**Comment by jorangreef** [comment]
Thanks @craig-mulligan and @jviotti, if Disk Utility repair does not work you could also try rebooting to see if `osascript -e 'do shell script "echo foo" with administrator privileges'` works after reboot (this has helped others), or else reinstall macOS over your existing macOS.

**Comment by lurch** [comment]
> The source of the sudo-prompt-command script is written out dynamically during exec() here: https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L244

I'm a Linux-user rather than a Mac-user (so I don't know how the permission system works on macOS), but does that assume that the program that's making use of `sudo-prompt` is itself stored in a writable directory? What happens if the program that's making use of `sudo-prompt` is stored in a readonly directory?

**Comment by jorangreef** [comment]
Hi Andrew

Thanks for the question, the write is done to a tmp directory not to the application directory. This tmp directory is versioned using a UUID to prevent collisions with other sudo prompt instances, and is cleaned up after use.

Joran

On 28 Nov 2017, at 16:17, Andrew Scheller <notifications@github.com> wrote:

The source of the sudo-prompt-command script is written out dynamically during exec() here: https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L244

I'm a Linux-user rather than a Mac-user (so I don't know how the permission system works on macOS), but does that assume that the program that's making use of sudo-prompt is itself stored in a writable directory? What happens if the program that's making use of sudo-prompt is stored in a readonly directory?

**Comment by lurch** [comment]
Ahh, thanks for the great answer Joran :-)

**Comment by jorangreef** [comment]
@craig-mulligan any progress with your Mac?

**Comment by jviotti** [comment]
Ping @hobochild

**Comment by jorangreef** [comment]
Thanks, not sure how I got @craig-mulligan!

**Comment by lurch** [comment]
Looks like he renamed his GH username ;-)

**Comment by hobochild** [comment]
Hey @jorangreef cc @jviotti @lurch. 

rebooting and repairing the drive didn't seem to work. But I completely formatted the drive and reinstalled macos and now `osascript -e 'do shell script "echo foo" with administrator privileges'` opens the sudo prompt as expected. 

Looks like it was likely a broken macOS installation as @jviotti pointed to earlier. 

Thanks all!

**Comment by jorangreef** [comment]
Thanks @hobochild @jviotti !
