### ISSUE TITLE
Don't use child_process.exec() on GNU/Linux

### ISSUE THREAD

**Issue by jviotti** [jorangreef/sudo-prompt#66]
We recently hit a weird issue where a process spawned with this module would log a lot verbose output to `stdout`, and eventually cause a "stdout maxBuffer size exceeded." on GNU/Linux.

Can we replace `.exec()` with `.spawn()` [here](https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L128) and collect the output by listening to child stdio events to avoid this from happening even in the worst case?

See https://github.com/resin-io/etcher/pull/1961

**Comment by jorangreef** [comment]
Thanks @jviotti 

I have some ideas on a solution, but here's the back-story on this first.

We should use `spawn()` if we could. The reasons we don't so far:

* I couldn't find any way to get access to the AppleScript's stdio streams using Node's `spawn()` directly on macOS, so `sudo-prompt.spawn()` would not be cross-platform. Perhaps you can find a way?

* We could solve the issue above on macOS by recreating Node's `spawn()` interface (and guarantees and edge-cases) using files, but this would be months of work.

* Exposing `spawn()` would enlarge sudo-prompt's interface surface area significantly. It limits the chances of adding further platforms where `spawn()` might not work. Ideally, the interface surface area should be as small as possible to limit bugs and improve reliability. This means we have fewer invariants to maintain cross-platform.

Related issues:

https://github.com/jorangreef/sudo-prompt/issues/54
https://github.com/jorangreef/sudo-prompt/issues/50

Regarding a solution to your issue, we only hit the `maxBuffer` limit on Linux. We already tolerate very large buffers on macOS and Windows since we simply call `readFile()` on the final stdout and stderr files: https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L311

What if we pass an arbitrary 128mb `maxBuffer` option to `exec()` on Linux ? This would not be user-configurable since this would increase surface area and we would then need to introduce fake limits for macOS and Windows which already use files.

Another solution would be to return a stream instance which we pipe into from the stdout and stderr files on macOS, and from the child process on Linux.

**Comment by jorangreef** [comment]
Just bumping the maxBuffer on Linux would be much simpler for now.

**Comment by jviotti** [comment]
@jorangreef I think my original message was a bit confusing. I was not proposing to replace `sudoPrompt.exec` with a new `sudoPrompt.spawn`, but to keep the `sudoPrompt.exec()` interface while using `child_process.spawn()` under the hood to collect output from the `pkexec`/`kdesu` commands here: https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L128. For example:

```js
const child = Node.child.spawn(command[0], [ args ])

let stdout = ''
let stderr = ''

child.stdout.on('data', (data) => stdout += data.toString())
child.stderr.on('data', (data) => stderr += data.toString())

child.on('close', () => {
  end(null, stdout, stderr);
})
```

Accumulating stdout/stderr this way should avoid the `maxBuffer` error while still allowing users to log as much as they want.

**Comment by jorangreef** [comment]
Yes, that's what I understood. We don't need to use `spawn()` like that there on line 128, we can just pass a custom very large `options.maxBuffer` limit to `child_process.exec()`:

https://nodejs.org/dist/latest-v9.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by jviotti** [comment]
Cool, I'm happy with that!

**Comment by jorangreef** [comment]
Thanks, fixed in https://github.com/jorangreef/sudo-prompt/commit/0ba8cf0b2789bca08e8a2de99c39fe49ce6e4792
