### ISSUE TITLE
Is there a way to ask for the permission just once?

### ISSUE THREAD

**Issue by baristaGeek** [jorangreef/sudo-prompt#84]
Is there a way to ask for the credentials just once? In other words, is it possible to give root permissions to an Electron app using sudo-prompt?

The problem is that I'm trying to run a command that is previously defined from iterating an array of 15,000 elements and gathering the data of each iteration. Since this makes sudo-prompt try to generate 15,000 prompts at once, the system crashes.

How do I make sudo-prompt ask for the password just once?

**Comment by jorangreef** [comment]
Due to system TTY tickets on Linux and macOS this is not possible.

You will need to improve your design to ask for the credentials using sudo-prompt just once and then make the most of those privileges by doing everything you need to do.

For example, you can move your 15,000 tasks into a single script, then run that script using sudo-prompt.

This is mentioned in the README here: https://github.com/jorangreef/sudo-prompt#concurrency

**Comment by NargisTahara** [comment]
I have the same issue.

https://stackoverflow.com/questions/54652002/how-can-i-take-persistent-permissions-in-electron-app

I need to execute commands at different point of time. @baristaGeek  How did you solve your problem. Is it possible to launch a child process with sudo rights using sudo-prompt? 
Something like that:

`var  terminal = cProcess.spawn('sudo',['bash']);`

This code unfortunately will not issue a permission dialogue, that's why not possible to use in an Electron app.

**Comment by NargisTahara** [comment]
@jorangreef how did you created a dialogue for user input. Spawning sudo as a child process will ask for user permissions on terminal, while I want to ask these permission as a dialogue like sudo-prompt.
