### ISSUE TITLE
An additional env variable is needed when working under a non-English linux platform.

### ISSUE THREAD

**Issue by ppoffice** [jorangreef/sudo-prompt#9]
According to https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L20, sudo-prompt uses regular expression to detect whether to show a prompt dialog. But under different language environments this does not always work. So here is my temporary solution:
```js
const SUDO_OPTION = {
    name: APP_NAME,
    process: {
        options: {
            env: { 'LANG': 'en_US.UTF-8' }
        }
    }
};
```

**Comment by jorangreef** [comment]
Thanks.

Would you please paste the full output of running the following in your locale with the different language:

```
sudo -k && sudo -n echo hello
```

**Comment by ppoffice** [comment]
![image](https://cloud.githubusercontent.com/assets/8849362/12070830/65b91eaa-b0c6-11e5-8998-ae3d0eb17efd.png)

```
ppoffice@ppoffice-VirtualBox:~$ sudo -k & sudo -n echo hello
[1] 2070
sudo: 需要密码
[1]+  已完成               sudo -k
```

**Comment by jorangreef** [comment]
Should be fixed with https://github.com/jorangreef/sudo-prompt/commit/d08ec680f3317d1ebbdcc6ca990f9988a61b7cf2, please let me know if this works.

There may still be a locale language dependency on Linux (https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L168), but this should only affect the error message returned, an error should still be returned regardless of language, so I think that is fine for now.

**Comment by ppoffice** [comment]
Thx :+1:
